events {}

http {
  server {
    listen 80;
    server_name api.karitheattempt.com list.karitheattempt.com;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://$host$request_uri; }
  }

  server {
    listen 443 ssl;
    server_name api.karitheattempt.com;
    ssl_certificate /etc/letsencrypt/live/api.karitheattempt.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.karitheattempt.com/privkey.pem;

    location /songs {
      limit_except GET {
        auth_basic "Admin";
        auth_basic_user_file /etc/nginx/.htpasswd;
      }
      add_header Access-Control-Allow-Origin *;
      proxy_pass http://songs-api:3000;
    }

    location /admin {
      auth_basic "Admin";
      auth_basic_user_file /etc/nginx/.htpasswd;
      proxy_pass http://songs-api:3000;
    }
  }

  server {
    listen 443 ssl;
    server_name list.karitheattempt.com;
    ssl_certificate /etc/letsencrypt/live/api.karitheattempt.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.karitheattempt.com/privkey.pem;

    location / {
      proxy_pass http://listmonk:9000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
